import json
ov = json.load(open("runtime/overview.json"))
print("=== RANGKUMAN MODAL ===")
print(f"Balance      : {ov.get('balance',0):.2f}")
print(f"Equity       : {ov.get('equity',0):.2f}")
print(f"Floating P/L : {ov.get('floating_pl',0):.2f}")
print(f"Margin       : {ov.get('margin',0):.2f}")
print(f"Free Margin  : {ov.get('margin_free',0):.2f}")
print(f"Margin Level : {ov.get('margin_level',0):.2f}")
print(f"Drawdown     : {ov.get('drawdown',0):.2f}")
print()
print("=== HARI INI ===")
print(f"Trades       : {ov.get('trades_today',0)}")
print(f"Profit       : {ov.get('profit_today',0):.2f}")
print()
print("=== ALL-TIME ===")
lr = ov.get('learning',{})
print(f"Total        : {lr.get('total',0)} trades")
print(f"Win / Loss   : {lr.get('win',0)} / {lr.get('loss',0)}")
print(f"Win Rate     : {lr.get('win_rate',0)}%")
print()
print("=== POSISI ===")
print(f"Open         : {ov.get('open_count',0)}")
print(f"Signal       : {ov.get('signal','-')}")
print(f"Grade        : {ov.get('score','-')}")
print(f"Reason       : {ov.get('reason','-')}")
